# This is a basic workflow to test SpatialPy

name: SpatialPy Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Print info
        run: |
         pwd
         ls -lah

      - name: Build docker image
        run: docker-compose build

      - name: Run unit tests
        run: docker-compose run notebook coverage run spatialpy/test/test.py 
